function tf = is_double_single_2d_matrix(x)
    tf =  (...
            strcmp(string(class(x)),"double") ...
            || strcmp(string(class(x)),"single")...
           )...
          && (numel(x) ~= max(size(x))) ...
          && numel(size(x)) == 2;
end
