function tf = is_double_single_scalar(x)
    tf =  (...
            strcmp(string(class(x)),"double") ...
            || strcmp(string(class(x)),"single")...
           )...
          && (numel(x) == 1);
end