function tf = is_double_single_logical_scalar(x)
tf =(...
        strcmp(string(class(x)),"double")...
        ||strcmp(string(class(x)),"single")...
        ||strcmp(string(class(x)),"logical")...
    )...
    && numel(x) == 1;

end

